FROM ruby:3.0.2

RUN apt-get update &&  apt-get install -y \
  build-essential \
  default-libmysqlclient-dev \
  imagemagick \
  git-core \
  && apt-get autoremove \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV RAILS_ROOT /app
ENV REDIS_URL=redis://redis:6379/1

WORKDIR $RAILS_ROOT

COPY Gemfile Gemfile.lock ./
RUN gem install bundler
RUN bundle install 

COPY . ./
CMD ["sidekiq", "-C", "config/sidekiq.yml"]
